name: Deploy PR Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: sin
  FLY_ORG: personal

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v6.0.2
        with:
            lfs: true
      - name: Git Describe
        id: ghd
        uses: proudust/gh-describe@v2
        with:
          default: '0.0'
      - name: Get App Version from Git Describe
        env:
          APPVER: ${{ steps.ghd.outputs.describe }}
        run: echo $APPVER | sed -E 's/^([0-9]+\.[0-9]+)\.?[0-9]*-([0-9]+)/\1\.\2/; s/\-g[0-9a-f]+//; s/^/VITE_APP_VERSION=/' >> $GITHUB_ENV
      - name: Deploy Preview
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        with:
          build_args: "APPVER=${{ env.VITE_APP_VERSION }}"
  preview-cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Remove Preview
        uses: superfly/fly-pr-review-apps@1.5.0
      - name: Get GitHub App token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: pr-${{ github.event.number }}