name: Deploy PR Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: sin
  FLY_ORG: personal

jobs:
  get-version:
    outputs:
      APPVER: ${{ steps.getver.outputs.APPVER }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: '0'
      - name: Get Version
        id: getver
        run: git describe --tags --long --always | sed -E 's/^([0-9]+\.[0-9]+)\.?[0-9]*-([0-9]+)/\1\.\2/; s/\-g[0-9a-f]+//; s/^/APPVER=/' >> $GITHUB_OUTPUT
  preview-deploy:
    needs: get-version
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
            lfs: true
      - name: Git Describe
        id: ghd
        uses: proudust/gh-describe@80412be8ce0e77d8afba6b340e34790bc772aa45 # v2
        with:
          default: '0.0'
      - name: Get App Version from Git Describe
        env:
          APPVER: ${{ needs.get-version.outputs.APPVER }}
        run: echo $APPVER | sed -E 's/^([0-9]+\.[0-9]+)\.?[0-9]*-([0-9]+)/\1\.\2/; s/\-g[0-9a-f]+//; s/^/VITE_APP_VERSION=/' >> $GITHUB_ENV
      - name: Deploy Preview
        id: deploy
        uses: superfly/fly-pr-review-apps@f5d85309215d5700e7a42faf9aa5e9a718aaef7c # 1.5.0
        with:
          build_args: "APPVER=${{ needs.get-version.outputs.APPVER }}"
  preview-cleanup:
    needs: get-version
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Remove Preview
        uses: superfly/fly-pr-review-apps@f5d85309215d5700e7a42faf9aa5e9a718aaef7c # 1.5.0
      - name: Get GitHub App token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@608de24d085d9f1f0e45f5df0c3b7c0907d6881a # v3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: pr-${{ github.event.number }}